import { Router, Request, Response } from 'express';
import express from 'express';
import Stripe from 'stripe';
import { prisma } from '../lib/prisma';
import { generateScript, generateResearchBrief } from '../lib/gemini';
import { fetchYouTubeInsights } from '../lib/research';
import { renderPackReportHtml } from '../lib/render';
import {
  sendPackDelivery,
  sendConciergeDelivery,
  sendInternalConciergeAlert,
  sendFailureAlert,
} from '../lib/resend';
import { getActivePrompt } from '../lib/promptVersions';

const router = Router();

router.use(express.raw({ type: 'application/json' }));

const FRONTEND_URL = process.env.FRONTEND_URL ?? 'https://clipscriptai.com';

// FIX: was duplicate data_drop — replaced with series_episode for 5 unique types
const PACK_SCRIPT_TYPES = [
  'niche_tip',
  'data_drop',
  'trend_take',
  'niche_tip_basic',
  'series_episode',
] as const;

// Singleton Stripe client
let _stripe: Stripe | null = null;
function getStripe(): Stripe {
  if (!_stripe) {
    if (!process.env.STRIPE_SECRET_KEY) throw new Error('STRIPE_SECRET_KEY is not set');
    _stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
  }
  return _stripe;
}

// ---------------------------------------------------------------------------
// Stripe webhook
// ---------------------------------------------------------------------------
router.post('/stripe', async (req: Request, res: Response) => {
  const sig = req.headers['stripe-signature'];
  if (!sig) {
    res.status(400).json({ error: 'Missing stripe-signature header' });
    return;
  }

  const stripe = getStripe();
  let event: Stripe.Event;

  try {
    event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_WEBHOOK_SECRET!);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    res.status(400).json({ error: `Webhook signature verification failed: ${msg}` });
    return;
  }

  // Respond immediately — Stripe requires < 30s
  res.json({ received: true });

  if (event.type !== 'checkout.session.completed') return;

  const session = event.data.object as Stripe.Checkout.Session;
  const email = session.customer_details?.email ?? (session.metadata?.email ?? '');
  const stripePaymentId =
    typeof session.payment_intent === 'string'
      ? session.payment_intent
      : session.id;
  const niche = session.metadata?.niche ?? '';
  const topic = session.metadata?.topic ?? '';
  const brief = session.metadata?.brief ?? '';
  const orderType = session.metadata?.orderType ?? 'concierge';
  const platform = session.metadata?.platform ?? '';
  const stage = session.metadata?.stage ?? '';
  const audience = session.metadata?.audience ?? '';
  const goals = session.metadata?.goals ?? '';

  // Validate email — can't deliver without one
  if (!email) {
    console.error(`[webhook] No email found for payment ${stripePaymentId} — cannot deliver`);
    await sendFailureAlert({
      orderEmail: '(no email)',
      stripePaymentId,
      orderType,
      niche,
      topic,
      errorMessage: 'No customer email found on checkout session',
    });
    return;
  }

  // Persist order (reportToken auto-generated by DB default)
  const order = await prisma.conciergeOrder.upsert({
    where: { stripePaymentId },
    update: {},
    create: { stripePaymentId, email, niche, topic, orderType, brief, platform, stage, audience, goals },
  });

  // Idempotency: bail if already delivered (Stripe webhook retries)
  if (order.scriptDelivered) {
    console.log(`[webhook] Order ${stripePaymentId} already delivered — skipping`);
    return;
  }

  const reportUrl = order.reportToken
    ? `${FRONTEND_URL}/report/${order.reportToken}`
    : undefined;

  if (orderType === 'pack') {
    try {
      // A/B test: each pack script uses dynamic prompt versioning (80/20 current/challenger)
      const scripts = await Promise.all(
        PACK_SCRIPT_TYPES.map(async (scriptType) => {
          const { prompt } = await getActivePrompt(scriptType);
          return generateScript(
            {
              niche: niche || 'general lifestyle',
              scriptType,
              additionalContext: topic ? `Focus on this topic: ${topic}` : undefined,
            },
            prompt,
          );
        }),
      );

      const reportHtml = renderPackReportHtml(scripts, niche || 'lifestyle', topic);

      // Send email FIRST, then mark as delivered
      await sendPackDelivery({
        toEmail: email,
        scripts,
        niche: niche || 'lifestyle',
        topic,
        reportUrl,
      });

      // Only mark delivered after email succeeds
      await prisma.conciergeOrder.update({
        where: { stripePaymentId },
        data: { scriptDelivered: true, reportHtml },
      });
    } catch (err) {
      console.error('Pack generation failed:', err);
      await sendFailureAlert({
        orderEmail: email,
        stripePaymentId,
        orderType,
        niche,
        topic,
        errorMessage: err instanceof Error ? err.message : String(err),
      });
    }
  } else {
    // Concierge — full research brief
    // FIX: moved inside try/catch so failure doesn't kill the whole flow
    try {
      await sendInternalConciergeAlert({ orderEmail: email, niche, topic, brief, stripePaymentId });
    } catch (alertErr) {
      console.error('Internal concierge alert failed (non-fatal):', alertErr);
    }

    try {
      // 1. Fetch real YouTube performance data
      const { summary: youtubeInsights } = await fetchYouTubeInsights(
        topic || niche,
        niche || 'general lifestyle',
      );

      // 2. Generate full research brief as HTML
      const reportHtml = await generateResearchBrief({
        niche: niche || 'general lifestyle',
        topic,
        brief,
        audience,
        platform,
        stage,
        goals,
        youtubeInsights,
      });

      // 3. Also generate one ready-to-film script for the email
      const additionalContext = [
        topic && `Topic and angle: ${topic}`,
        brief && `Additional context: ${brief}`,
        audience && `Target audience: ${audience}`,
        'Make this exceptional — paid concierge order.',
      ]
        .filter(Boolean)
        .join('\n');

      const sampleScript = await generateScript({
        niche: niche || 'general lifestyle',
        scriptType: 'niche_tip',
        additionalContext,
      });

      // Send email FIRST, then mark as delivered
      await sendConciergeDelivery({
        toEmail: email,
        sampleScript,
        niche: niche || 'lifestyle',
        topic,
        reportUrl,
      });

      // Only mark delivered after email succeeds
      await prisma.conciergeOrder.update({
        where: { stripePaymentId },
        data: { scriptDelivered: true, reportHtml, brief, platform, stage, audience, goals },
      });
    } catch (genErr) {
      console.error('Concierge generation failed:', genErr);
      await sendFailureAlert({
        orderEmail: email,
        stripePaymentId,
        orderType,
        niche,
        topic,
        errorMessage: genErr instanceof Error ? genErr.message : String(genErr),
      });
    }
  }
});

// ---------------------------------------------------------------------------
// RevenueCat webhook
// ---------------------------------------------------------------------------
router.post('/revenuecat', async (req: Request, res: Response) => {
  const authHeader = req.headers.authorization;
  if (authHeader !== `Bearer ${process.env.REVENUECAT_WEBHOOK_SECRET}`) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }

  let body: any;
  try {
    body = JSON.parse(req.body.toString());
  } catch {
    res.status(400).json({ error: 'Invalid JSON body' });
    return;
  }

  const { event } = body;
  if (!event) {
    res.json({ received: true });
    return;
  }

  const { type, app_user_id: clerkUserId, product_id } = event;

  const tierMap: Record<string, string> = {
    founders_annual: 'founders',
    pro_monthly: 'pro',
    pro_annual: 'pro',
  };
  const scriptsPerDayMap: Record<string, number> = { founders: 5, pro: 5, free: 1 };

  if (['INITIAL_PURCHASE', 'RENEWAL', 'REACTIVATION'].includes(type)) {
    const tier = tierMap[product_id] ?? 'pro';
    await prisma.tenant.updateMany({
      where: { clerkUserId },
      data: { tier, scriptsPerDay: scriptsPerDayMap[tier] ?? 5 },
    });
  }

  if (['EXPIRATION', 'CANCELLATION'].includes(type)) {
    await prisma.tenant.updateMany({
      where: { clerkUserId },
      data: { tier: 'free', scriptsPerDay: 1 },
    });
  }

  res.json({ received: true });
});

export default router;
